using VideoForensics.Api.Contracts;
using VideoForensics.Data.Core.Contracts;
using VideoForensics.Data.Core.Models;
using VideoForensics.WebApp.Auth;

namespace VideoForensics.WebApp.Api
{
    /// <summary>
    /// Forensic report generation endpoints (read-only operations that build reports from stored evidence).
    ///
    /// AUTHENTICATION & AUTHORIZATION: These endpoints are gated by RequireAuthorization() since they are
    /// paired-device-only operations (chain-of-custody forensic reports). All report generation methods
    /// are read-only: they synthesize reports from existing evidence data without creating server-side
    /// artifacts (WriteReportAsync does that and requires step-up). Consequently:
    /// - GET endpoints (report generation) do NOT require step-up re-authentication
    /// - POST endpoint (WriteReportAsync to file artifact) DOES require step-up re-authentication,
    ///   as it creates a new artifact that will be exported; see the specific endpoint's WithDescription
    ///   for reasoning.
    ///
    /// The design rationale: report GENERATION is a forensic analysis operation over read-only data;
    /// exporting that report to a file (WriteReportAsync) is a destructive action creating new artifacts
    /// subject to evidence chain-of-custody controls, hence step-up applies to the export, not the read.
    /// </summary>
    public static class ReportEndpoints
    {
        public static void MapReportEndpoints(this WebApplication app)
        {
            RouteGroupBuilder group = app.MapGroup("/api/v1/reports")
                .RequireAuthorization();

            _ = group.MapGet("/evidence-review", BuildEvidenceReviewReportAsync)
                .RequireRateLimiting("media")
                .WithSummary("Generate evidence review report")
                .WithDescription("Builds an evidence review report listing media items and their integrity verification status over the specified time window.");

            _ = group.MapGet("/forensic-analysis", BuildForensicAnalysisReportAsync)
                .RequireRateLimiting("media")
                .WithSummary("Generate forensic analysis report")
                .WithDescription("Builds a comprehensive forensic analysis report summarizing evidence, device health anomalies, and significant actions across devices.");

            _ = group.MapGet("/signal-anomaly", BuildSignalAnomalyReportAsync)
                .RequireRateLimiting("media")
                .WithSummary("Generate signal anomaly report")
                .WithDescription("Builds a signal anomaly report analyzing device health metrics and identifying connectivity issues like signal degradation or jamming.");

            _ = group.MapGet("/access-control", BuildAccessControlReportAsync)
                .RequireRateLimiting("media")
                .WithSummary("Generate access control report")
                .WithDescription("Builds an access control report showing who accessed and exported evidence during the specified period.");

            _ = group.MapGet("/chain-of-custody", BuildChainOfCustodyReportAsync)
                .RequireRateLimiting("media")
                .WithSummary("Generate chain of custody report")
                .WithDescription("Builds a chain of custody report showing the complete hash-chained audit trail for evidence integrity verification.");

            _ = group.MapPost("/write", WriteReportAsync)
                .AddEndpointFilter<StepUpEndpointFilter>()
                .RequireRateLimiting("media")
                .WithSummary("Export report to file")
                .WithDescription("Writes a report (generated by one of the report endpoints above) to a file in the specified format (json, xml, csv). " +
                    "This operation creates a new artifact subject to evidence chain-of-custody controls, hence requires step-up re-authentication.");
        }

        private static async Task<IResult> BuildEvidenceReviewReportAsync(
            Guid? deviceId,
            DateTime? fromUtc,
            DateTime? toUtc,
            IReportGenerationService reportService,
            CancellationToken ct)
        {
            try
            {
                DateTime from = fromUtc ?? DateTime.UtcNow.AddDays(-7);
                DateTime to = toUtc ?? DateTime.UtcNow;

                EvidenceReviewReport report = await reportService.BuildEvidenceReviewAsync(deviceId, from, to, ct);
                return Results.Ok(report.ToDto());
            }
            catch (Exception ex)
            {
                return Results.BadRequest(new { error = $"Failed to generate evidence review report: {ex.Message}" });
            }
        }

        private static async Task<IResult> BuildForensicAnalysisReportAsync(
            Guid? deviceId,
            DateTime? fromUtc,
            DateTime? toUtc,
            IReportGenerationService reportService,
            CancellationToken ct)
        {
            try
            {
                DateTime from = fromUtc ?? DateTime.UtcNow.AddDays(-7);
                DateTime to = toUtc ?? DateTime.UtcNow;

                ForensicAnalysisReport report = await reportService.BuildForensicAnalysisReportAsync(deviceId, from, to, ct);
                return Results.Ok(report.ToDto());
            }
            catch (Exception ex)
            {
                return Results.BadRequest(new { error = $"Failed to generate forensic analysis report: {ex.Message}" });
            }
        }

        private static async Task<IResult> BuildSignalAnomalyReportAsync(
            Guid? deviceId,
            DateTime? fromUtc,
            DateTime? toUtc,
            IReportGenerationService reportService,
            CancellationToken ct)
        {
            try
            {
                DateTime from = fromUtc ?? DateTime.UtcNow.AddDays(-7);
                DateTime to = toUtc ?? DateTime.UtcNow;

                SignalAnomalyReport report = await reportService.BuildSignalAnomalyReportAsync(deviceId, from, to, ct);
                return Results.Ok(report.ToDto());
            }
            catch (Exception ex)
            {
                return Results.BadRequest(new { error = $"Failed to generate signal anomaly report: {ex.Message}" });
            }
        }

        private static async Task<IResult> BuildAccessControlReportAsync(
            Guid? deviceId,
            DateTime? fromUtc,
            DateTime? toUtc,
            IReportGenerationService reportService,
            CancellationToken ct)
        {
            try
            {
                DateTime from = fromUtc ?? DateTime.UtcNow.AddDays(-7);
                DateTime to = toUtc ?? DateTime.UtcNow;

                AccessControlReport report = await reportService.BuildAccessControlReportAsync(deviceId, from, to, ct);
                return Results.Ok(report.ToDto());
            }
            catch (Exception ex)
            {
                return Results.BadRequest(new { error = $"Failed to generate access control report: {ex.Message}" });
            }
        }

        private static async Task<IResult> BuildChainOfCustodyReportAsync(
            Guid? deviceId,
            DateTime? fromUtc,
            DateTime? toUtc,
            IReportGenerationService reportService,
            CancellationToken ct)
        {
            try
            {
                DateTime from = fromUtc ?? DateTime.UtcNow.AddDays(-7);
                DateTime to = toUtc ?? DateTime.UtcNow;

                ChainOfCustodyReport report = await reportService.BuildChainOfCustodyReportAsync(deviceId, from, to, ct);
                return Results.Ok(report.ToDto());
            }
            catch (Exception ex)
            {
                return Results.BadRequest(new { error = $"Failed to generate chain of custody report: {ex.Message}" });
            }
        }

        private static async Task<IResult> WriteReportAsync(
            WriteReportRequest request,
            IReportGenerationService reportService,
            CancellationToken ct)
        {
            try
            {
                await reportService.WriteReportAsync(request.ReportDto, request.Format, ct);
                return Results.Ok(new { message = "Report successfully exported to file." });
            }
            catch (Exception ex)
            {
                return Results.BadRequest(new { error = $"Failed to write report: {ex.Message}" });
            }
        }
    }

    /// <summary>Request for writing a report to file.</summary>
    /// <param name="ReportDto">The report DTO to write (one of: EvidenceReviewReportDto, ForensicAnalysisReportDto, SignalAnomalyReportDto, AccessControlReportDto, ChainOfCustodyReportDto).</param>
    /// <param name="Format">Export format: "json", "xml", or "csv".</param>
    public record WriteReportRequest(
        object ReportDto,
        string Format
    );
}
