<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="core.forensics/VideoForensics.Forensics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis" Version="5.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="**\Tests\**" />
    <Compile Remove="core.forensics\**\*.cs" />
    <Compile Remove="core.forensics-tests\**\*.cs" />
  </ItemGroup>

</Project>
