using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace KoenZomers.Ring.Api.Entities
{
    /// <summary>
    /// A single classified detection within a CV-evaluated event, with the timestamps (epoch ms)
    /// it was confirmed at. Confirmed via a live ApiTester run of video_search/history and
    /// locations/{id}/events.
    /// </summary>
    public class CvDetectionType
    {
        [JsonPropertyName("detection_type")]
        public string DetectionType { get; set; }

        [JsonPropertyName("verified_timestamps")]
        public List<long> VerifiedTimestamps { get; set; }
    }

    /// <summary>
    /// Computer vision properties returned by the Ring API for a history event.
    /// Indicates whether the Ring backend detected a person (or other classified object) in the recording.
    /// </summary>
    public class CvProperties
    {
        /// <summary>
        /// When true, Ring's computer vision detected a person in the recording.
        /// May be null if the event was not evaluated by CV (e.g. rings, older firmware, etc.).
        /// </summary>
        [JsonPropertyName("person_detected")]
        public bool? PersonDetected { get; set; }

        /// <summary>
        /// When true, Ring indicated the recording stream was broken / incomplete.
        /// </summary>
        [JsonPropertyName("stream_broken")]
        public bool? StreamBroken { get; set; }

        /// <summary>
        /// The classified detection type reported by Ring (e.g. "human", "vehicle", "animal", "other_motion").
        /// </summary>
        [JsonPropertyName("detection_type")]
        public string DetectionType { get; set; }

        /// <summary>
        /// The individual classified detections (each with its own confirmation timestamps) that
        /// make up this event's overall <see cref="DetectionType"/>.
        /// </summary>
        [JsonPropertyName("detection_types")]
        public List<CvDetectionType> DetectionTypes { get; set; }

        /// <summary>
        /// Security alerts/annotations detected by Ring AI analysis for this event.
        /// Null if no security analysis performed.
        /// </summary>
        [JsonPropertyName("security_alerts")]
        public CvSecurityAlerts SecurityAlerts { get; set; }

        /// <summary>
        /// Person profiles detected and matched in this event (recognized faces/identities).
        /// Null if face recognition not available or no matches found.
        /// </summary>
        [JsonPropertyName("profiles")]
        public List<CvProfile> Profiles { get; set; }

        /// <summary>
        /// Detailed event description generated by Ring AI analysis.
        /// Example: "Person detected at front door"
        /// </summary>
        [JsonPropertyName("full_description")]
        public string FullDescription { get; set; }

        /// <summary>
        /// Brief event description generated by Ring AI analysis.
        /// Shorter version of FullDescription.
        /// </summary>
        [JsonPropertyName("short_description")]
        public string ShortDescription { get; set; }

        /// <summary>
        /// Confidence score for detection/analysis match (0.0 to 1.0).
        /// Null if not computed.
        /// </summary>
        [JsonPropertyName("similarity")]
        public double? Similarity { get; set; }

        /// <summary>
        /// Anomaly score for unusual activity (0.0 to 1.0).
        /// Null if anomaly detection not performed.
        /// </summary>
        [JsonPropertyName("anomaly")]
        public double? Anomaly { get; set; }

        /// <summary>
        /// Detailed metadata about detection confidence, zones, and other diagnostic info.
        /// Null if detection details not available.
        /// </summary>
        [JsonPropertyName("detection_details")]
        public CvDetectionDetails DetectionDetails { get; set; }

        /// <summary>
        /// User-applied or AI-suggested tags/labels for this event.
        /// Null if no tags present.
        /// </summary>
        [JsonPropertyName("tags")]
        public List<string> Tags { get; set; }
    }

    /// <summary>
    /// Security alerts/annotations from Ring AI analysis.
    /// </summary>
    public class CvSecurityAlerts
    {
        [JsonPropertyName("severity")]
        public string Severity { get; set; }

        [JsonPropertyName("alerts")]
        public List<string> Alerts { get; set; }
    }

    /// <summary>
    /// A person profile detected and identified (via face recognition) in an event.
    /// </summary>
    public class CvProfile
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("confidence")]
        public double? Confidence { get; set; }

        [JsonPropertyName("thumbnail_url")]
        public string ThumbnailUrl { get; set; }
    }

    /// <summary>
    /// Detailed detection metadata including zones and confidence values.
    /// </summary>
    public class CvDetectionDetails
    {
        [JsonPropertyName("zones")]
        public List<CvZone> Zones { get; set; }

        [JsonPropertyName("confidence")]
        public double? Confidence { get; set; }

        [JsonPropertyName("model_version")]
        public string ModelVersion { get; set; }
    }

    /// <summary>
    /// A motion detection zone within the video frame.
    /// </summary>
    public class CvZone
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("confidence")]
        public double? Confidence { get; set; }
    }
}
