// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoForensics.Data.Database.DbContext;

#nullable disable

namespace VideoForensics.Data.Database.Sqlite.Migrations
{
    [DbContext(typeof(VideoForensicsDbContext))]
    partial class VideoForensicsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.AccessAuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AccessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessedAtUtc");

                    b.HasIndex("EvidenceId");

                    b.HasIndex("UserId");

                    b.ToTable("AccessAuditLogs");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.ActionLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ActorType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousEntryHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("ActionLogEntries");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.AiAnalysisMotionZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiAnalysisSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AiAnalysisSnapshotId");

                    b.HasIndex("AiAnalysisSnapshotId", "ZoneId")
                        .IsUnique();

                    b.ToTable("AiAnalysisMotionZones");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.AiAnalysisSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullDescription")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PersonDetected")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DownloadEventId");

                    b.ToTable("AiAnalysisSnapshots");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.AiAnalysisTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiAnalysisSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AiAnalysisSnapshotId");

                    b.HasIndex("AiAnalysisSnapshotId", "TagName")
                        .IsUnique();

                    b.ToTable("AiAnalysisTags");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveProviderAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptionProvider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RotatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderAccountId");

                    b.HasIndex("ProviderAccountId", "CredentialType")
                        .IsUnique();

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.DetectedPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "ProfileId");

                    b.ToTable("DetectedPersons");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.DetectionTypeOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectionType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemDetectionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemDetectionId");

                    b.ToTable("DetectionTypeOccurrences");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.DetectionZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemDetectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemDetectionId", "ZoneId");

                    b.ToTable("DetectionZones");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiResponseHash")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceFeaturesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceHealthId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceLocationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPullAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulPullAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDeviceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("LocationId", "ProviderDeviceId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.DeviceAlerts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlertType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "AlertType");

                    b.ToTable("DeviceAlerts");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.DeviceCapabilities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiResponseHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("HardwareModel")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasAudio")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasCloudStorage")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasMotionDetection")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasNightVision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxStorageDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceCapabilities");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.DeviceConfigSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomSettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("MotionDetectionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotionSensitivity")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordingMode")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceConfigSnapshots");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.DeviceFeatures", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AdvancedMotionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("MotionMessageEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("MotionsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("NightVisionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("PeopleOnlyEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ShadowCorrectionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ShowRecordings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceFeatures");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.DeviceHealth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BatteryPercentage")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BatteryVoltageValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsExternalPowerConnected")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtaStatus")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("WifiName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WifiSignalRssi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CapturedAtUtc");

                    b.ToTable("DeviceHealths");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.DeviceHealthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BatteryPercentage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Connected")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DownloadEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rssi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WifiName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadEventId");

                    b.HasIndex("DeviceId", "CapturedAtUtc");

                    b.ToTable("DeviceHealthSnapshots");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.DeviceLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceLocations");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.DownloadEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Answered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DownloadCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DownloadStartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventOccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Favorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordingStatus")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DeviceId", "ProviderEventId")
                        .IsUnique();

                    b.ToTable("DownloadEvents");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiSourceHash")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DownloadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DownloadFailedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EventDetectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventIntegrityHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordingStatus")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EventDetectionId");

                    b.HasIndex("DeviceId", "ProviderEventId")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.EventDetectedPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventDetectedPersons");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.EventDetection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Anomaly")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectionType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullDescription")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PersonDetected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Similarity")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("StreamBroken")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventDetections");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.EventDetectionTypeOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectionType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventDetectionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventDetectionId");

                    b.ToTable("EventDetectionTypeOccurrences");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.EventDetectionZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventDetectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventDetectionId", "ZoneId");

                    b.ToTable("EventDetectionZones");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.EventSecurityAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlertText")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventSecurityAlerts");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.ExportAuditRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventsExported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExportFormat")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExportedAtUtc");

                    b.HasIndex("LocationId");

                    b.ToTable("ExportAuditRecords");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.ExportRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchiveFileName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchiveSha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseReference")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportedByUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipientDescription")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasEncrypted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExportedAtUtc");

                    b.ToTable("ExportRecords");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.ExportRecordItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExportRecordId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaItemSha256HashAtExport")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExportRecordId");

                    b.HasIndex("MediaItemId");

                    b.ToTable("ExportRecordItems");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.IntegrityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("IntegrityRecords");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.JammingIncidentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AffectedEventCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageDegradationDb")
                        .HasColumnType("REAL");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("JammingIncidentRecords");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.JammingStatsSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageDegradationDb")
                        .HasColumnType("REAL");

                    b.Property<int>("DefiniteConfidenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstIncidentUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("HighConfidenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastIncidentUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LowConfidenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxDegradationDb")
                        .HasColumnType("REAL");

                    b.Property<int>("MediumConfidenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalJammedDurationMinutes")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("JammingStatsSummaries");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.LegalHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("LegalHolds");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiResponseHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderLocationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderLocationId")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.LocationMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiResponseHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsOwner")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("LocationMetadata");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiSourceHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioCodec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DownloadEventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DownloadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FrameRate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IntegrityVerified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPurged")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastVerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaFormat")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaItemDetectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurgeReason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurgedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DownloadEventId");

                    b.HasIndex("Sha256Hash");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.MediaItemDetection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Anomaly")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectionType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullDescription")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PersonDetected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Similarity")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("StreamBroken")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("MediaItemDetections");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.OperatorPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CultureName")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId")
                        .IsUnique();

                    b.ToTable("OperatorPreferences");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.PairedDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FallbackApiKeyHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSeenTier")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PairedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PinnedCertificateFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebAuthnCredentialId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("WebAuthnPublicKey")
                        .HasColumnType("BLOB");

                    b.Property<uint>("WebAuthnSignCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FallbackApiKeyHash");

                    b.HasIndex("OperatorId");

                    b.HasIndex("WebAuthnCredentialId");

                    b.ToTable("PairedDevices");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.ProviderAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDownloadTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulAuthUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LinkedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ProviderName")
                        .IsUnique();

                    b.ToTable("ProviderAccounts");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.ProviderApiCallRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName", "TimestampUtc");

                    b.ToTable("ProviderApiCallRecords");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.ProviderApiErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCategory")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("DeviceId", "OccurredAtUtc");

                    b.ToTable("ProviderApiErrorLogs");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.ProviderReconciliationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscrepancyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderValue")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RanAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredValue")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("ProviderReconciliationRecords");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.RingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiResponseHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuthenticatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderAccountId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RateLimitPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RateLimitRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RingAccountFeaturesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionLevel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderAccountId")
                        .IsUnique();

                    b.HasIndex("RingAccountFeaturesId");

                    b.ToTable("RingAccounts");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.RingAccountFeatures", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("CanActivateAlarmSystem")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanChangeDeviceSettings")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanDeleteRecordings")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanPauseRecordings")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanSaveLiveView")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanSaveRecordings")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanShareRecordings")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanViewLiveView")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanViewRecordings")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanViewSnapshotsOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RingAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RingAccountId");

                    b.ToTable("RingAccountFeatures");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.SecurityAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlertText")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("SecurityAlerts");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.SecurityAuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PairedDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("SecurityAuditLogEntries");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderUserKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderUserKey")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.AiAnalysisMotionZone", b =>
                {
                    b.HasOne("VideoForensics.Data.Common.Entities.AiAnalysisSnapshot", "AiAnalysisSnapshot")
                        .WithMany("MotionZones")
                        .HasForeignKey("AiAnalysisSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiAnalysisSnapshot");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.AiAnalysisTag", b =>
                {
                    b.HasOne("VideoForensics.Data.Common.Entities.AiAnalysisSnapshot", "AiAnalysisSnapshot")
                        .WithMany("Tags")
                        .HasForeignKey("AiAnalysisSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiAnalysisSnapshot");
                });

            modelBuilder.Entity("VideoForensics.Data.Common.Entities.AiAnalysisSnapshot", b =>
                {
                    b.Navigation("MotionZones");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
