namespace VideoForensics.Data.Common.Entities
{
    /// <summary>An alert generated by the system, typically for security or jamming events.</summary>
    public class Alert
    {
        /// <summary>Gets or sets the alert ID.</summary>
        public Guid Id { get; set; }

        /// <summary>Gets or sets the alert title (required, max 256 chars) — e.g., "Jamming Detected".</summary>
        public required string Title { get; set; }

        /// <summary>Gets or sets the alert description (nullable, max 4000 chars) — summary text incorporating event details.</summary>
        public string? Description { get; set; }

        /// <summary>Gets or sets the ID of the related forensic case, if any (nullable).</summary>
        public Guid? RelatedCaseId { get; set; }

        /// <summary>Gets or sets the alert status (required, max 64 chars) — e.g., "Open", "Closed", "Acknowledged".</summary>
        public required string Status { get; set; }

        /// <summary>Gets or sets the username or system identifier who created this alert (required, max 256 chars).</summary>
        public required string CreatedBy { get; set; }

        /// <summary>Gets or sets the alert type/category (required, max 64 chars) — e.g., "JammingDetection".</summary>
        public required string AlertType { get; set; }

        /// <summary>Gets or sets the UTC timestamp when the alert was created.</summary>
        public DateTime CreatedAtUtc { get; set; }

        /// <summary>Gets or sets the UTC timestamp of the most recent update to this alert (nullable).</summary>
        public DateTime? UpdatedAtUtc { get; set; }
    }
}
