<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsTestProject>true</IsTestProject>
        <AssemblyName>VideoForensics.Providers.Ring.Core.Tests</AssemblyName>
        <RootNamespace>VideoForensics.Providers.Ring.Core.Tests</RootNamespace>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>..\..\..\KoenZomers.RingApi.snk</AssemblyOriginatorKeyFile>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis" Version="5.9.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
        <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Ring.Api.Core.csproj" />
        <ProjectReference Include="../../../src/auth/Ring.Api.Auth.csproj" />
        <ProjectReference Include="../../../src/video/Ring.Api.Video.csproj" />
    </ItemGroup>

</Project>



