<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>VideoForensics.Providers.Ring</RootNamespace>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>../../../../KoenZomers.RingApi.snk</AssemblyOriginatorKeyFile>
        <AssemblyName>VideoForensics.Providers.Ring.Video</AssemblyName>
        <Company>Koen Zomers</Company>
        <Authors>Koen Zomers, Daniel Espinosa</Authors>
        <Description>Recording download/streaming primitives for Ring.Api</Description>
        <Copyright>Koen Zomers</Copyright>
        <PackageLicenseExpression> EPL-2.0</PackageLicenseExpression>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../../../KoenZomers.RingApi.snk" Link="KoenZomers.RingApi.snk" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="tests/**/*.cs" />
        <Compile Remove="metadata/**/*.cs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis" Version="5.9.0" />
    </ItemGroup>

</Project>



