<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>VideoForensics.Providers.Wyze</RootNamespace>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>../../../../KoenZomers.RingApi.snk</AssemblyOriginatorKeyFile>
        <AssemblyName>VideoForensics.Providers.Wyze.Core</AssemblyName>
        <Company>Video Forensics</Company>
        <Authors>Video Forensics Team</Authors>
        <Description>Core functionality for Wyze API integration</Description>
        <Copyright>Video Forensics</Copyright>
        <PackageLicenseExpression>EPL-2.0</PackageLicenseExpression>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../../../KoenZomers.RingApi.snk" Link="KoenZomers.RingApi.snk" />
        <ProjectReference Include="../common/VideoForensics.Providers.Wyze.Common.csproj" />
        <ProjectReference Include="../auth/VideoForensics.Providers.Wyze.Auth.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="tests/**/*.cs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis" Version="5.9.0" />
    </ItemGroup>

</Project>
