<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Ring.Api</RootNamespace>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>../../KoenZomers.RingApi.snk</AssemblyOriginatorKeyFile>
        <AssemblyName>Ring.Api.Core</AssemblyName>
        <Company>Koen Zomers</Company>
        <Authors>Koen Zomers, Daniel Espinosa</Authors>
        <Description>Core session and service implementations for Ring.Api</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Copyright>Koen Zomers</Copyright>
        <PackageLicenseExpression> EPL-2.0</PackageLicenseExpression>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../KoenZomers.RingApi.snk" Link="KoenZomers.RingApi.snk" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
        <PackageReference Include="SIPSorcery" Version="10.0.16" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../common/Ring.Api.Common.csproj" />
        <ProjectReference Include="../auth/Ring.Api.Auth.csproj" />
        <ProjectReference Include="../video/Ring.Api.Video.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="tests/**" />
    </ItemGroup>

</Project>



