<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Ring.Api</RootNamespace>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>../../KoenZomers.RingApi.snk</AssemblyOriginatorKeyFile>
        <AssemblyName>Ring.Api.Common</AssemblyName>
        <Company>Koen Zomers</Company>
        <Authors>Koen Zomers, Daniel Espinosa</Authors>
        <Description>Common interfaces, entities, and exceptions for Ring.Api</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Copyright>Koen Zomers</Copyright>
        <PackageLicenseExpression> EPL-2.0</PackageLicenseExpression>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../KoenZomers.RingApi.snk" Link="KoenZomers.RingApi.snk" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="tests/**" />
    </ItemGroup>

</Project>



