name: Publish - Stable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: extract
        shell: bash
        run: |
          dotnet tool update --global nbgv
          export PATH="$PATH:$HOME/.dotnet/tools"
          VERSION=$(nbgv get-version -v Version)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Detected version: $VERSION"

  publish-nuget:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/pack-nuget-packages.yml
    needs: [get-version]
    with:
      version: ${{ needs.get-version.outputs.version }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
